-- 1. List the following details of each employee: employee number, last name, first name, sex, and salary.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, EMPLOYEES.SEX, 
	SALARIES.SALARY
FROM EMPLOYEES
JOIN SALARIES
ON SALARIES.EMP_NO = EMPLOYEES.EMP_NO;

-- 2.List first name, last name, and hire date for employees who were hired in 1986.
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE RIGHT(HIRE_DATE, 4) = '1986';

-- 3.List the manager of each department with the following information: department number, department name, 
-- the manager's employee number, last name, first name.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	DEPT_MANAGER.DEPT_NO, DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_MANAGER
ON EMPLOYEES.EMP_NO = DEPT_MANAGER.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_MANAGER.DEPT_NO;

-- 4. List the department of each employee with the following information: employee number, last name, 
-- first name, and department name.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	DEPT_EMP.DEPT_NO, DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_EMP
ON EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_EMP.DEPT_NO;

-- 5. List first name, last name, and sex for employees whose first name is "Hercules" and last names 
-- begin with "B."
SELECT FIRST_NAME, LAST_NAME, SEX 
FROM EMPLOYEES
WHERE FIRST_NAME = 'Hercules'
AND LEFT(LAST_NAME,1) = 'B';

-- 6. List all employees in the Sales department, including their employee number, last name, 
-- first name, and department name.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_MANAGER
ON EMPLOYEES.EMP_NO = DEPT_MANAGER.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_MANAGER.DEPT_NO
WHERE DEPARTMENTS.DEPT_NAME = 'Sales'

UNION ALL

SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	 DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_EMP
ON EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_EMP.DEPT_NO
WHERE DEPARTMENTS.DEPT_NAME = 'Sales';

-- 7. List all employees in the Sales and Development departments,
-- including their employee number, last name, first name, and department name.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_MANAGER
ON EMPLOYEES.EMP_NO = DEPT_MANAGER.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_MANAGER.DEPT_NO
WHERE DEPARTMENTS.DEPT_NAME = 'Sales'
OR DEPARTMENTS.DEPT_NAME = 'Development'

UNION ALL

SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, 
	 DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
JOIN DEPT_EMP
ON EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
JOIN DEPARTMENTS
ON DEPARTMENTS.DEPT_NO = DEPT_EMP.DEPT_NO
WHERE DEPARTMENTS.DEPT_NAME = 'Sales'
OR DEPARTMENTS.DEPT_NAME = 'Development';

-- 8. In descending order, list the frequency count of employee last names, 
-- i.e., how many employees share each last name.
SELECT LAST_NAME,
	COUNT(LAST_NAME) AS "Count"
FROM EMPLOYEES
GROUP BY LAST_NAME
ORDER BY "Count" DESC